"""
create text transformations table
"""

from yoyo import step

__depends__ = {}

steps = [
    step(
        """
        CREATE TABLE   (
            id UUID PRIMARY KEY,
            number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
            original_text VARCHAR(1024),
            transformed_text VARCHAR(2000),
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
            user_id UUID REFERENCES users(id) DEFAULT NULL ON DELETE SET NULL
        );
        
        -- Индекс для ускорения поиска по number
        CREATE INDEX idx_texts_number ON texts(number);
        """,
        """
        DROP INDEX IF EXISTS idx_texts_number;
        DROP TABLE texts;
        """,
    )
]
